site_name: pytaxize
site_description: Taxonomic toolbelt for Python
site_url: https://pytaxize.readthedocs.io
repo_url: https://github.com/sckott/pytaxize
repo_name: sckott/pytaxize
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

plugins:
  - search

nav:
  - Home: index.md
  - API Reference:
      - Overview: api/overview.md
      - Core Functions: api/tax.md
      - Scientific Names: api/scicomm.md
      - Taxonomic IDs: api/ids.md
      - ITIS: api/itis.md
      - NCBI: api/ncbi.md
      - Catalogue of Life: api/col.md
      - Global Names: api/gn.md
      - Children: api/children.md
      - Classification: api/classification.md
      - Utilities: api/utils.md
  - Examples:
      - Getting Started: examples/getting-started.md
      - Common Use Cases: examples/common-use-cases.md
  - Contributing: contributing.md
  - Changelog: changelog.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sckott/pytaxize
  version:
    provider: mike
